export const LightTheme = [
  {name: '--bg-color', value: 'var(--light)'},
  {name: '--second-color', value: 'var(--white)'},
  {name: '--bg-messanger', value: 'var(--white)'},
  {name: '--header-text', value: 'var(--white)'},
  {name: '--contacts-color', value: 'black'},
  {name: '--contacts-color-hover', value: 'var(--white-darker)'},
  {name: '--message-content', value: 'black'},
  {name: '--input-bg', value: 'var(--light)'},
  {name: '--input-holder', value: 'var(--light-dark)'},
  {name: '--input-text', value: 'black'},
  {name: '--menu-bg', value: 'var(--white)'},
  {name: '--menu-hover', value: 'var(--white-darker)'},
  {name: '--menu-color', value: 'black'},
  {name: '--popup-bg', value: 'var(--white)'},
]
