env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules:
  "semi": "warn"
  "no-unused-vars": ["warn"]
  "max-len": ["error", 100]
  "max-params": ["warn", 3]
