export const APP_LOGIN_USER = 'APP/LOGIN'
export const APP_LOGOUT_USER = 'APP/LOGOUT'
export const REQUEST_AUTH = 'APP/REQUEST_AUTH'
export const FETCH_CHATS_REQUEST = 'CONTACTS/REQUEST_CHATS'
export const FETCH_CHATS_SUCCESS = 'CONTACTS/REQUEST_CHATS_SUCCESS'
export const FETCH_CHATS_FAILURE = 'CONTACTS/REQUEST_CHATS_FAILURE'

